/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.temporalworker;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

@SpringBootTest
@TestPropertySource(properties = {
        "temporal.worker.enabled=false"
})
class AppTest {
    @Test void contextLoads() {}
}
